config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  get 'applications/create'

  get 'applications/show'

  get 'applications/index'

  get 'favourites/create'

  get 'favourites/show'

  get 'reviews/create'

  get 'users/show'

  get 'user/:id/profile', to: 'users#show' , as: 'user_profile'

  get 'users/update'

  get 'programs/show'

  get 'programs/index'

  get 'universities/show'

  get 'universities/index'

  get 'search', to: "programs#search", as: :search

  # devise_for :users
  root to: 'pages#home'

  resources :programs do
    resources :favourites, only: :create
    resources :reviews, only: :create

    resources :applications, only: :create

  end

# facebook
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :university
  has_many :favourites, dependent: :destroy
  has_many :users, through: :favourites
  has_many :applications , dependent: :destroy
  has_many :reviews, dependent: :destroy

  class << self
    def search(query)
      if query.is_a? String
        self.search_string(query)


      end
    end



    def search_string(quer)
     q = "%#{quer}%"
     self.where("title ILIKE ? OR subject ILIKE ? OR level ILIKE ?", q, q, q)
   end

   def search_modal(subject, level, location, tuit, scholarship)
    query = self

    query = query.where("subject ILIKE ? ", "%#{subject}%") if subject.present?
    query = query.where("level ILIKE ? ", "%#{level}%") if level.present?
    query = query.where("tuition < ?", tuit) if tuit.is_a?(Integer) and tuit > 0
    query = query.where("scholarship > ?", scholarship) if scholarship.is_a?(Integer) and scholarship > 0

    array_final = query

    if location.present?
      programs = University.where("location ILIKE ?", "%#{location}%").map {|university| university.programs }.flatten
      array_final = array_final.select { |x| programs.include?(x)}
    end

    array_final



      # data = [
      #   (subject.present?) ? self.where("subject ILIKE ?", q1) : [],
      #   (level.present?) ? self.where("level ILIKE ?", q2) : [],
      # #    (location.present?) ? University.where("location ILIKE ?", q3).map {|university| university.programs }.flatten : []
      # #       ]

      # array_f = self.where("subject ILIKE ? AND level ILIKE ? ", q1, q2)
      # array_g = University.where("location ILIKE ?", q3).map {|university| university.programs }.flatten

      # array = array_f.select{|x| array_g.include?(x)}
      # raise
      # if tuition =! 0
      #   return array_final = array.select{|x| tuition_array.include?(x)}
      # else
      #   return array
      # end

    end

    def search_city(c)
      cit = "%#{c}%"
      University.where("location ILIKE ?", cit).map {|university| university.programs }.flatten
    end

    def search_level(l)
      lev = "%#{l}%"
      self.where("level ILIKE ?", lev)
    end

    def search_tuition(t)
      self.where("tuition < ?", t)
    end

    def search_scholarship(s)
      self.where("scholarship < ?", s)
    end

  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:search, :show]

  def show
    @review = Review.new
    @program = Program.find(params[:id])
    if params[:notice]
      application = Application.new(user: current_user)
      application.program = @program
      flash[:notice] = "Succesfully applied to #{@program.title}"
    end
  end

  def index

  end



  def search
    @cities = %w(Italy Spain UK Germany Netherlands France)
    @level = %w(Master Bachelor MBA)
    @tuition = [1000, 5000, 10000, 50000]
    @subject = %w(Economics Management Mathematics Computer Finance Media Politics Actuarial Engineering Markeking Law Biology )
    @scholarship = [0, 1000, 5000, 10000]
    @hidden = true
    query = {}

    if params[:search_value].nil?
      # Run the modal sear

      @pippo = Program.search_modal(params[:subject], params[:level], params[:location], params[:tuition].to_i, params[:scholarship].to_i)
      @list = @pippo.map { |p| p.university }

      @hash = Gmaps4rails.build_markers(@list) do |uni, marker|
        marker.lat uni.latitude
        marker.lng uni.longitude
        marker.infowindow render_to_string(partial: "/universities/mapbox", locals: { uni: uni })
      end

    elsif params[:search_value]
      # Run classic search with value only
      @pippo = Program.search(params[:search_value]).select do |program|
        true
        # program.university and program.university.latitude and program.university.longitude
      end

      @list = @pippo.map { |p| p.university }

      @hash = Gmaps4rails.build_markers(@list) do |uni, marker|

        marker.lat uni.latitude
        marker.lng uni.longitude
        marker.infowindow render_to_string(partial: "/universities/mapbox", locals: { uni: uni })

      end

    else
      render :home
    end






  #   if params[:location] != ""
  #     @pippo = Program.search_city(params[:location]).select do |program|
  #       program.university and program.university.latitude and program.university.longitude
  #     end

  #     @list = @pippo.map { |p| p.university }


  #     @hash = Gmaps4rails.build_markers(@list) do |uni, marker|

  #       marker.lat uni.latitude
  #       marker.lng uni.longitude
  #     end
  #   end

  #   if params[:level] != ""

  #     @pippo = Program.search_level(params[:level]).select do |program|
  #       program.university and program.university.latitude and program.university.longitude
  #     end

  #     @list = @pippo.map { |p| p.university }


  #     @hash = Gmaps4rails.build_markers(@list) do |uni, marker|

  #       marker.lat uni.latitude
  #       marker.lng uni.longitude
  #     end
  #   end

  #   if params[:tuition] != ""
  #     @pippo = Program.search_tuition(params[:tuition]).select do |program|
  #       program.university and program.university.latitude and program.university.longitude
  #     end

  #     @list = @pippo.map { |p| p.university }


  #     @hash = Gmaps4rails.build_markers(@list) do |uni, marker|

  #       marker.lat uni.latitude
  #       marker.lng uni.longitude
  #     end
  #   end

  #   if params[:scholarship] != ""
  #     @pippo = Program.search_scholarship(params[:scholarship]).select do |program|
  #       program.university and program.university.latitude and program.university.longitude
  #     end

  #     @list = @pippo.map { |p| p.university }


  #     @hash = Gmaps4rails.build_markers(@list) do |uni, marker|

  #       marker.lat uni.latitude
  #       marker.lng uni.longitude
  #     end
  #   end
end
end

app/views/programs/_apply_card.html.erb
<div class="apply-card">
<% if params[:notice] %>
  <h4>
    Already applied
  </h4>
  <% else %>
  <button data-toggle="modal" class="btn btn-apply" data-target="#apply">Apply</button>
  <%= render partial: "apply_modal", locals: { program: program } %>
<% end %>
  <ul>
    <li>
      <h4>
        #<%= @program.ranking %>
      </h4>
      <strong>
        Ranking
      </strong>
    </li>
    <li>
    <h4>
        <%= @program.subject %>
      </h4>
      <strong>
        Subject
      </strong>
    </li>
    <li>
    <h4>
        <%= @program.tuition %>$
    </h4>
      <strong>
        Tuition Fees
      </strong>
    </li>
    <li>
    <h4>
        <%= @program.scholarship %>$
    </h4>
      <strong>
        Scholarship Opportunities
      </strong>
    </li>
  </ul>
</div>

app/views/programs/_apply_modal.html.erb
<div class="modal modal-apply text-center fade" id="apply">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="exampleModalLabel">My Application</h4>
    </div>
    <div class="modal-body">
      <form>
        <div class="form-group">
          <label for="applicant-name" class="control-label">First Name</label>
          <input type="text" class="form-control" id="applicant-name">
        </div>
        <div class="form-group">
          <label for="last-name" class="control-label">Last Name</label>
          <textarea class="form-control" id="last-name"></textarea>
        </div>
        <div class="form-group">
          <label for="motivation-text" class="control-label">Motivation</label>
          <textarea class="form-control" id="motivation-text"></textarea>
        </div>
      </form>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <div class="text-center">

      <%= link_to "Apply", program_path(program, :notice => "You have applied to #{program.title}"), :class => "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/programs/_card.html.erb
<!-- <div class="container">
  <div class="row"> -->
  <!-- <style>
    .card-search:hover {
      background-image: linear-gradient(rgba(38,39,38,0.3) 100%, rgba(38,39,38,0.18) 100%)!important;
    }
  </style> -->
    <div class="card-program card-search m-button" style="background-image:linear-gradient(rgba(26,39,38,0.6) 11%, rgba(-5,18,38,71.18) 100%),  url('<%= cl_image_path program.university.photos.first.path, height: 300, width: 400, crop: :mfit, gravity: :center; %>')">



      <%= link_to program_path(program), class: "card-search-link" do%>
        <div class="card-background">
            <p class="text-search" style="font-size: 19px; padding-top: 20px;"><strong><%= program.university.name %></strong></p>
            <h3 class="text-center letter-spacing" style="margin-top: 0px";><%= program.title  %></h3>
            <p class="text-search"> <%= program.university.location %></p>
        </div>

        <div class="card-footer col-xs-6">
          <p class="text-center text-footer">Subject
            <br>
            <strong><span class="span-footer"><%= program.subject %></strong></span></p>
            <br>
            <div class="verticalLine"></div>
            <p class="text-center text-footer">Tuition<br><strong><span class="span-footer">$<%= program.tuition %></strong></span></p>
        </div>
      <% end %>
    </div>

app/views/programs/_carrousel_program_show.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));" role="listbox">
  <% program.university.photos.each_with_index do |thing, index| %>
    <div class="item <%= "active" if index.zero? %>">
      <img style="width: 100%; height: auto" src="<%= cl_image_path thing.path, width: 1000, height: 500, crop: :fill %>" alt="">
    </div>
    <% end %>

  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/programs/_content_search.html.erb
<div class="container" id="map-button-container">
  <div class="line"></div>
  <div class="map-button">
    <%= link_to 'View Map', '#', id: 'view_map', class: "view-map btn btn-map", style:"
    padding: 12px;" %>
  </div>
  <div class="line"> </div>


</div>

<div class="row">
  <div class="col-xs-12">
    <% programs.each do |program| %>
    <div class="col-xs-4">
      <%= render 'card', program: program %>
    </div>
    <% end %>
  </div>
</div>

</div>

app/views/programs/_favourite_card.html.erb
<div class="favourite-card">
  <h4>
    Are you interested in this program?
  </h4>
  <ul>
    <% if current_user.favourite_programs.include?(program) %>
    <li>
      <p>
        Already favourited <i class="fa fa-heart"></i>
      </p>
    </li>
    <% else %>
    <li>
      <%= simple_form_for program, url: program_favourites_path(program), method: :post do |f| %>
      <%= f.submit "Favourite this" %> <span><i class="fa fa-heart"></i></span>
      <% end %>
    </li>
    <% end %>

    <% if current_user %>
    <li>
      <%= link_to " My Favourites", user_profile_path(current_user) %>
    </li>
    <% end %>
  </ul>
  <div data-href="http://www.yooni.life" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore facebook-button" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fyooni.herokuapp.com%2F&amp;src=sdkpreparse">
  <i class="fa fa-facebook"></i>
    Share
  </a>
</div>

</div>

app/views/programs/_generic_info_card.html.erb
<div class="favourite-card generic-info-card">
  <ul>
    <li>
      <%= @program.university.phone_number %>
    </li>
    <li>
      <%= @program.university.contact %>
    </li>
    <li>
      <strong> <%= link_to @program.university.website, @program.university.website %> </strong>
    </li>
  </ul>
</div>

app/views/programs/_program_content.html.erb
<div class="content-card">
  <h1><strong><%= @program.title %></h1></strong>
  <h2><%= @program.university.name %></h2>
  <div class="location">
    <i class="fa fa-map-marker"></i>
    <%= @program.university.location %>
  </div>
  <p class="description">
    <%= @program.university.description %>
  </p>
</div>

<%= render partial: "carrousel_program_show", locals: { program: @program } %>

app/views/programs/_sidebar.html.erb
<!-- Menu -->
<div class="side-menu">

  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="brand-wrapper">
        <!-- Hamburger -->
        <button type="button" class="navbar-toggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- Brand -->
        <div class="brand-name-wrapper">
          <a class="navbar-brand" href="#">
            Update your Search
          </a>
        </div>

        <!-- Search -->


        <!-- Search body -->
        <div id="search" class="panel-collapse">
          <div class="panel-body">
            <form class="navbar-form" role="search" method="get" action="/search">
              <div class="form-group">
                <input type="text" name="search_value" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default "><span class="glyphicon glyphicon-search"></span></button>
            </form>

          </div>
        </div>
      </div>

    </div>

    <!-- Main Menu -->
    <div class="side-menu-container">
      <ul class="nav navbar-nav">


        <!-- Dropdown-->
        <li class="panel panel-default" id="dropdown">
          <a data-toggle="collapse" href="#dropdown-lvl1">
            <i class="fa fa-map-marker" aria-hidden="true">  </i> Location <span class="caret"></span>
          </a>

          <!-- Dropdown level 1 -->
          <div id="dropdown-lvl1" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="nav navbar-nav">
                <% @cities.each do |city| %>

                <% search_filter = request.query_parameters.merge({location: city}) %>
                <% search_filter.delete(:search_value)   %>



                <li><%= link_to city, search_path(search_filter) %></li>
                <% end %>


              </ul>
            </div>
          </div>
        </li>

        <li class="panel panel-default" id="dropdown">
          <a data-toggle="collapse" href="#dropdown-lvl2">
            <i class="fa fa-graduation-cap" aria-hidden="true"></i>
 Level <span class="caret"></span>
          </a>

          <!-- Dropdown level 1 -->
          <div id="dropdown-lvl2" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="nav navbar-nav">
                <% @level.each do |lev| %>
                <% search_filter2 = request.query_parameters.merge({level: lev}) %>
                <% search_filter2.delete(:search_value)   %>

                <li><%= link_to lev, search_path(search_filter2) %></li>
                <% end %>


              </ul>
            </div>
          </div>
        </li>

        <li class="panel panel-default" id="dropdown">
          <a data-toggle="collapse" href="#dropdown-lvl3">
            <i class="fa fa-money" aria-hidden="true"></i> Tuition <span class="caret"></span>
          </a>

          <!-- Dropdown level 1 -->
          <div id="dropdown-lvl3" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="nav navbar-nav">
                <% @tuition.each do |tui| %>
                <% search_filter3 = request.query_parameters.merge({tuition: tui}) %>
                <% search_filter3.delete(:search_value)   %>
                <li><%= link_to "<#{tui}", search_path(search_filter3) %></li>
                <% end %>


              </ul>
            </div>
          </div>
        </li>

        <li class="panel panel-default" id="dropdown">
          <a data-toggle="collapse" href="#dropdown-lvl4">
            <i class="fa fa-book" aria-hidden="true"></i> Subject <span class="caret"></span>
          </a>

          <!-- Dropdown level 1 -->
          <div id="dropdown-lvl4" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="nav navbar-nav">
                <% @subject.each do |subi| %>
                <% search_filter4 = request.query_parameters.merge({subject: subi}) %>
                <% search_filter4.delete(:search_value)   %>
                <li><%= link_to subi, search_path(search_filter4) %></li>
                <% end %>


              </ul>
            </div>
          </div>
        </li>

        <li class="panel panel-default" id="dropdown">
          <a data-toggle="collapse" href="#dropdown-lvl5">
            <i class="fa fa-usd" aria-hidden="true"></i> Scholarship <span class="caret"></span>
          </a>

          <!-- Dropdown level 1 -->
          <div id="dropdown-lvl5" class="panel-collapse collapse">
            <div class="panel-body">
              <ul class="nav navbar-nav">
                <% @scholarship.each do |subi| %>
                <% search_filter5 = request.query_parameters.merge({scholarship: subi}) %>
                <% search_filter5.delete(:search_value)   %>
                <li><%= link_to ">#{subi}", search_path(search_filter5) %></li>
                <% end %>


              </ul>
            </div>
          </div>
        </li>



      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

</div>

app/views/programs/index.html.erb
<h1>Programs#index</h1>
<p>Find me in app/views/programs/index.html.erb</p>

app/views/programs/search.html.erb
 <%= render "sidebar" %>

 <!-- Main Content -->
<div class="container-fluid">
  <div class="side-body">
   <div id="map" class="toggle-map" style="width: 100%; height: 300px; float: right; center"></div>

      <%= render "content_search", programs: @pippo %>



   <% content_for(:after_js) do %>
     <%= javascript_tag do %>
         $(document).ready(function() {
         var handler = Gmaps.build('Google');
         handler.buildMap({ internal: { id: 'map' } }, function() {
         markers = handler.addMarkers(<%= raw @hash.to_json %>);
         handler.bounds.extendWith(markers);
         handler.fitMapToBounds();
         handler.map.centerOn([52.000000, 4.000000]);
         if (markers.length == 0) {
         handler.getMap().setZoom(2);
       } else if (markers.length == 1) {
       handler.getMap().setZoom(14);
      }
      });
      });
      <% end %>
    <% end %>

</div>
</div>

app/views/programs/show.html.erb
<div class="top-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-3">
        <%= render partial: "favourite_card", locals: { program: @program } %>
        <%= render partial: "generic_info_card", locals: { program: @program } %>
      </div>
      <div class="col-xs-6">
        <%= render partial: "program_content", locals: { program: @program } %>
      </div>
      <div class="col-xs-3">
        <%= render partial: "apply_card", locals: { program: @program } %>
      </div>
    </div>
  </div>
</div>