config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  get 'applications/create'

  get 'applications/show'

  get 'applications/index'

  get 'favourites/create'

  get 'favourites/show'

  get 'reviews/create'

  get 'users/show'

  get 'user/:id/profile', to: 'users#show' , as: 'user_profile'

  get 'users/update'

  get 'programs/show'

  get 'programs/index'

  get 'universities/show'

  get 'universities/index'

  get 'search', to: "programs#search", as: :search

  # devise_for :users
  root to: 'pages#home'

  resources :programs do
    resources :favourites, only: :create
    resources :reviews, only: :create

    resources :applications, only: :create

  end

# facebook
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
    @user = current_user
    @program = Program.find(params[:program_id])
    @review = Review.new(review_params)
    @review.program = @program
    @review.user = @user
    if @review.save
      redirect_to program_path(@program)
    else
      render 'programs/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/views/reviews/_form.html.erb
<%= simple_form_for [ program,review ], :url => program_reviews_path(:program_id => program.id), :method => :post   do |form| %>
  <%= form.input :content, as: :text %>
  <%= form.button :submit %>
<% end %>

app/views/reviews/_show.html.erb
<p><%= review.content %></p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>